services:
  db:
    image: postgres:13.1
    env_file:
      - environment.env
    restart: always
    healthcheck:
      test: "exit 0"
    volumes:
      - ~/aghour-services-data:/var/lib/postgresql
  
  redis:
    image: redis:6.0
    restart: always

  backend: 
    build: .
    entrypoint: /app/entrypoint.sh
    ports:
      - "8090:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - environment.env
    restart: always