version: "3"

services:
  redis:
    image: redis:6.0
    restart: always

  backend:
    build: .
    entrypoint: /app/entrypoint.sh
    ports:
      - "8090:3000"
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - environment.env
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  postgres:
  bundle_path:



