version: "3"

services:
  redis:
    image: redis:6.0
    restart: always
    networks:
      sharednetwork:
      
  backend: 
    build: .
    entrypoint: /app/entrypoint.sh
    ports:
      - "8090:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - environment.env
    networks:
      sharednetwork:
    restart: always

volumes:
  postgres:
  bundle_path:

networks:
  sharednetwork:
    name: "sharednet"

